name: Test
on: [push,  workflow_dispatch]
   
env:
   SCHEME_NAME: 'EhPanda'
   DEVELOPER_DIR: /Applications/Xcode_14.1.app
jobs:
  Test:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: brew install swiftgen
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Run tests
        run: xcodebuild clean test
          -scheme ${{ env.SCHEME_NAME }} -sdk iphonesimulator
          -destination 'platform=iOS Simulator,name=iPhone 14'
